services:
  - type: web
    name: the-shoe-boy
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_NAME
        value: "The Shoe Boy"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://the-shoe-boy.onrender.com"
      - key: ASSET_URL
        value: "https://the-shoe-boy.onrender.com"
      - key: APP_KEY
        value: "base64:ooDQex0Cr3QxZWMsy8Z3o90OUi1B4t+e4vSNkij+JpU="
      - key: DB_CONNECTION
        value: pgsql
      - fromDatabase:
          name: shoeboy-db
          property: connectionString
        key: DATABASE_URL
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync

databases:
  - name: shoeboy-db
    plan: free
    region: singapore
    databaseName: shoeboy
    user: shoeboy_user
